### ISSUE TITLE
Document usage in README.md

### ISSUE THREAD

**Issue by mtimofiiv** [mgmco/sepa-xml#2]
People will need to know how to use it properly!

**Comment by chrissvo** [comment]
People no longer need to know? Keep the masses stupid!

**Comment by chrissvo** [comment]
![image](https://cloud.githubusercontent.com/assets/2834982/9251883/a272e9e4-41d5-11e5-9490-ef60bd03f9de.png)

**Comment by mtimofiiv** [comment]
Oh, you...
