### ISSUE TITLE
NbOfTxs, CtrlSum is empty

### ISSUE THREAD

**Issue by denny99** [mgmco/sepa-xml#7]
The 001.001.03 template uses **{{_payments.info.transactionCount}}** for **NbOfTxs**, but **templateData** sets 

> this._payments.transactionCount = transactionCount;

as data. The same goes for CtrlSum/transactionControlSum

**Comment by mtimofiiv** [comment]
Hello @denny99, 

I fixed this here: https://github.com/mgmco/sepa-xml/commit/4a5b865f90666d4cdbf92db36f81ee7479dd696b
