### ISSUE TITLE
Using floating point summations

### ISSUE THREAD

**Issue by bramkoot** [mgmco/sepa-xml#9]
Hi, awesome library which passes the SEPA-tests of banks, except for the floating point calculations. Therefore I forked this one and added money-math to it, for safe summations. I'm happy to create a pull request to add in money-math or some decimal.js-like library, if the maintainer would like to add this to the library.

My fork is public on https://github.com/bramkoot/sepa-xml

**Comment by mtimofiiv** [comment]
Hi @bramkoot, thanks for helping out! Took a look at your fork, and if you submit a PR I will merge it in!

**Comment by mtimofiiv** [comment]
Hi @bramkoot, are you still interested in submitting the PR?

**Comment by bramkoot** [comment]
Yep, I actually made a slight adjustment and added Big.js instead of money-math because it's more flexible on input (money-math is super strict about input). This way the update is backwards compatible as far as I can see. I also adjusted the tests.

**Comment by mtimofiiv** [comment]
Great that it works with backwards compatibility! Published, as `0.3.0`
